#!/usr/bin/env bash
# APERTURE-CLEAN pre-compact.sh v1.1 | Enforce: SDO-H-05
# Extracts systemic failures and generates /compact preserve list.

LEDGER="FAILURE_LEDGER.md"
MAX_SIZE=102400 # 100KB
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

log_stderr() {
  echo "$@" >&2
}

# Initialize ledger if missing
if [[ ! -f "$LEDGER" ]]; then
  echo "# Persistent Failure Ledger" > "$LEDGER"
  echo "" >> "$LEDGER"
  echo "> Auto-generated by pre-compact.sh" >> "$LEDGER"
fi

# SECTION 1: GIT STATE SNAPSHOT
MODIFIED_FILES=$(git diff --name-only 2>/dev/null | tr '\n' ',' | sed 's/,$//')
STAGED_FILES=$(git diff --name-only --cached 2>/dev/null | tr '\n' ',' | sed 's/,$//')
BRANCH=$(git branch --show-current 2>/dev/null)

# SECTION 2: TRANSCRIPT EXTRACTION
# RESTRICTED: mktemp | REQUIRED: static temp file in .claude/snapshots
TEMP_FAILURES=".claude/snapshots/last_failures.tmp"
mkdir -p .claude/snapshots

# Extract patterns from STDIN (piped by Claude Code)
while IFS= read -r line; do
  if echo "$line" | grep -qiE "Error:|Failed:|Exception|exit code [1-9]|Permission denied|Access forbidden|blocked by rules|violates|RESTRICTED|forbidden pattern"; then
    echo "$line" >> "$TEMP_FAILURES"
  fi
done

# Process extractions
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  TYPE="UNKNOWN"
  if echo "$line" | grep -qiE "error|failed|exception|exit"; then TYPE="TE"; fi
  if echo "$line" | grep -qiE "permission|access|blocked"; then TYPE="SV"; fi
  if echo "$line" | grep -qiE "violates|RESTRICTED|forbidden"; then TYPE="CV"; fi

  PATTERN=$(echo "$line" | tr -d '*`#' | head -c 100)

  if ! grep -qF "$PATTERN" "$LEDGER"; then
    cat >> "$LEDGER" <<EOF
---
**Timestamp:** $TIMESTAMP | **Type:** $TYPE | **Branch:** $BRANCH
**Pattern:** $PATTERN
**Severity:** MAJOR
---
EOF
  fi
done < "$TEMP_FAILURES"
rm -f "$TEMP_FAILURES"

# SECTION 3: PRESERVE COMMAND GENERATION
echo "### COMPACTION RESTORE COMMAND"
if [[ -n "$MODIFIED_FILES" ]]; then
  echo "/compact preserve: [$MODIFIED_FILES]"
else
  echo "_No modified files detected._"
fi
